### ISSUE TITLE
Assembly Guide Prototype 3

### ISSUE THREAD

**Issue by Lobotuerk** [LucidVR/lucidgloves#1]
Do you have a video or a guide to assembly prototype 3? The videos on your channel show one of the older ones, and I printed the parts for the 3.1 and have no idea how to assembly it. Thanks in advance

**Comment by lucas-vrtech** [comment]
I am going to be posting a video tutorial on youtube soon.

**Comment by CameronKlinge** [comment]
i need help with wiring, so I see that on the wiring demonstration it shows how to wire to the AO A1 and so on but the other 2 pins on the petameter I don't get how to wire those. btw im wiring it without a breadboard.

**Comment by lucas-vrtech** [comment]
@CameronKlinge The other two pins correspond to GND and 5V. It needs to be split from the Arduino so that each potentiometer can get GND and 5V. (Or 3V3 if using an ESP32)

This guide may help:
https://www.arduino.cc/en/tutorial/potentiometer

**Comment by CameronKlinge** [comment]
@lucas-vrtech Ok that makes more sense thank you so much!

**Comment by danwillm** [comment]
Going to close this now that the tutorial is out, but please do feel free to re-open if you need more clarification.

https://www.youtube.com/watch?v=Qj4hqRKiy8g

**Comment by Lobotuerk** [comment]
Thank you @danwillm and @lucas-vrtech , Awesome work
