### ISSUE TITLE
CV1 controller tracking

### ISSUE THREAD

**Issue by Whheat** [LucidVR/lucidgloves#108]
I’m yet to built my gloves as I’m waiting for the next prototype but could you theoretically use the Rift CV1 controllers for tracking? I’ve heard legends of how excellent the controllers are and how durable they are. I feel like it could be done if I had the cameras set up right so the tracking rings facing upward could be tracked.

**Comment by lucas-vrtech** [comment]
Yes! The CV1 controllers are awesome for VR gloves. 
In fact, back in prototype 3 and earlier, [that was my preferred way of tracking the gloves.](https://www.tiktok.com/@lucas_vrtech/video/6926639197319171333) 

That being said, I don't know of any way to use the CV1 controllers without also using the CV1 HMD.
