### ISSUE TITLE
Quest 3?

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [LucidVR/lucidgloves#115]
I'm part of a group that's looking to build a set of these gloves for a project. We're currently deciding which headset to purchase, but we don't know if these work on quest 3. I'm guessing the shape is close enough where the mount will still work, but I'm worried about tracking. From what I read, it looks like they use combination hand tracking and a few IR light tracking points. I'm concerned it won't be able to track when the lights are occluded because hand tracking may not work. Has anyone tested this yet?

**Comment by MasterSiu** [comment]
It doesn't work outside steam vr at the moment

**Comment by TheBlueOompaLoompa** [comment]
I should clarify, I am writing a custom driver to connect it to quest headsets in my unity project, but I was wondering if someone had tested it in Steam VR with quest link. Specifically because the new method for controller tracking on the quest 3 seems to rely on hand tracking to fill in for when the tracking lights were occluded.

**Comment by danwillm** [comment]
When using the steamvr driver we've developed for the gloves, quest 3 is supported fine.
