### ISSUE TITLE
OBJ or  similar file type for the 3d parts?

### ISSUE THREAD

**Issue by MJ26gaming** [LucidVR/lucidgloves#18]
The STLs work fine for 3d printing, but having OBJs or STEPs for them so that way we can edit and customize them in CAD software would be nice

**Comment by NSP13737** [comment]
I know it's not the best solution, but if you just download blender you can really quickly import the file as an STL and then export it as an OBJ

**Comment by lucas-vrtech** [comment]
Currently, I am not releasing the step files for the entire glove itself, but will be probably releasing step files for the modular controller mount system soon. This may change in the future.
