### ISSUE TITLE
Deleting Closed Issues might be a Problem.

### ISSUE THREAD

**Issue by gaming-se** [LucidVR/lucidgloves#2]
I noticed the issues that been made, got closed and deleted. Closing Issues is not a problem but if you delete Issues the users that done the work to write a good issue report get less from doing it, it's like the work of doing a good and detailed report never existed.

Sometimes Users want to do a reference from new report to old issues and sometimes there are solutions in issues or other things that might be useful in this or other projects.

**Comment by lucas-vrtech** [comment]
This repo was recreated on github, no issues were deleted. All new issues will be permanent :)
