### ISSUE TITLE
ESP32s not sending/recieving

### ISSUE THREAD

**Issue by JamesPCVR** [LucidVR/lucidgloves#22]
I have uploaded the software to both gloves and have connected them to my computer over Bluetooth. The opengloves driver is able to track their position but I have no button inputs, finger tracking or haptic feedback. I am able to perform auto-calibration in the driver but not extend/retract the servos fully, I'm just told the command could not be added to the pipeline.

The configuration in the opengloves driver is as follows:
Both gloves enabled
Communication method Bluetooth serial
Right name: lucidgloves-right (same for firmware and serial number)
Left name: lucidgloves-left (same for firmware and serial number)
Driver emulation: lucid glove
Encoding protocol: Alpha

Any fixes?

**Comment by lucas-vrtech** [comment]
Are you able to check the bluetooth output in arduino IDE over bluetooth serial port numbers?

**Comment by Zach710032** [comment]
Change your comms method to usb serial and use the serial monitor(in arduino ide go to tools>serial monitor and then change baud rate to 115200) to see if your pots are actually sending positional data to the Esp32s and then to the computer. then, make sure you have the comms method changed back to btserial when you have verified the positional tracking works. Make sure opengloves is enabled in steam, and try flipping your pot values if you think you may have wired them backwards.

**Comment by danwillm** [comment]
In addition to this, SteamVR must be open for those functions to work. In a later release, this won't be needed.

**Comment by lucas-vrtech** [comment]
Closing this issue for now, if you're still running into problems, feel free to re-open or reach out over discord :)
