### ISSUE TITLE
I can't print green pot sliders without supports

### ISSUE THREAD

**Issue by Boaztheostrich** [LucidVR/lucidgloves#24]
The printing guide says that all parts can be printed without support

**Comment by 0611zman** [comment]
> The printing guide says that all parts can be printed without support

If you want to ping me in the discord server I can try to help you! Its "0611zman"

**Comment by Boaztheostrich** [comment]
I may tmw thanks!

**Comment by lucas-vrtech** [comment]
Closing the issue for now, if the issue isn't resolved feel free to re-open or DM me on discord :)
