### ISSUE TITLE
Licensing Agreement

### ISSUE THREAD

**Issue by daleyjem** [LucidVR/lucidgloves#28]
Be sure to update your licencing agreement(s) based on how you'd like your work and contributors' work to continue for the life of this, and future projects. Even if your demands are simple, they can still help spread the word of your project. Props to YouTube pubs like [The Mysticle](https://www.youtube.com/watch?v=1ZJNX8JCDOc) and [ThrillSeeker](https://www.youtube.com/watch?v=laZOSSEGqq8) for mentioning the project, but don't let your work go unnoticed.

You don't have to be a lawyer to do this, but at least be cognizant of how your code is shared.

Even at least put some kind of simple clause at the bottom (i.e.):

`LICENSE` file:

```md
  Any publicly shared use of this code requires at least a mention to its author.
```

... And go on from there.

**Comment by Blackclaws** [comment]
If you take a look at the existing license in the root folder it already stipulates:

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

You do not want to go around adding random things to open source licenses as that might very well make them unusable in most contexts as they are now a "self-modified" version which no lawyer has looked at, making them poison for most companies.

The MIT license is fine as is imho. If you want a license that does even more mentioning you could switch to Apache 2 which requires written info about the author of components at runtime as well.
