### ISSUE TITLE
Code more buttons

### ISSUE THREAD

**Issue by Reru01** [LucidVR/lucidgloves#32]
Hey, could you add code that allows for adding more buttons? I want to have 9 buttons on my device because I run out of buttons on my index controller that has 3, so adding the ability for people to add more buttons to the gloves natively allows for even better and more customized DIY gloves... I have another friend that wants to add like 12+ buttons to a glove if they ever make them.

**Comment by danwillm** [comment]
This isn't something that we're looking to implement in the near future, though it is certainly possible to extend both the driver and firmware to allow for this. There is some difficulty in getting hand tracking to work along with non-index controllers (some games don't enable finger tracking unless there are index controllers present, though there are ways around this), but if you do decide to fork off your own firmware and driver to allow for more buttons than feel free to reach out and we can help with those problems.
