### ISSUE TITLE
Arduino IMU Tracking?

### ISSUE THREAD

**Issue by Vansick1** [LucidVR/lucidgloves#35]
Would it be feasible to add Arduino-based tracking with a gyroscope/accelerometer sensor? That would allow for tracking that doesn't require existing VR controllers / trackers, since Vive tracker pucks are kinda pricey.

**Comment by hardlite** [comment]
Unfortunately, IMU tracking is both beyond the scope of this project, and wouldn't be nearly reliable enough to be a viable tracking method. As it stands, IMUs have too much inherent drift to viable in and of themselves as a tracking method.

**Comment by LittleNyanCat** [comment]
This has been asked many times in our discord server and short answer is no. Even SlimeVR will most likely to be too innacurate/drifty for something that requires precision like your hands

**Comment by lucas-vrtech** [comment]
Closing for the same reason LittleNyanCat mentioned. IMU based tracking could be used for wrist tracking, which would allow you to place your controller/tracker further up the arm, but that's about it unfortunately, until there's a really good DIY solution to counter IMU drift. Hopefully the SlimeVR guys can get it more accurate someday that we can work together on some cool hand tracking solution.
