### ISSUE TITLE
Unable to load configuration, please open an issue on GitHub: OpenVR Init Error

### ISSUE THREAD

**Issue by SB2203** [LucidVR/lucidgloves#38]
Hello everyone :)
Loading the firmware on the ESP32 worked as planned, but as soon as I started "open gloves" on steam, I got the error message written in the title. Serial and BT connection both result in the same error.

**Comment by LittleNyanCat** [comment]
Just to check, you got SteamVR installed and running, yes?

**Comment by SB2203** [comment]
yes it is running

**Comment by danwillm** [comment]
You'll also need to make sure that you have a headset connected. Do you have one connected?

**Comment by SB2203** [comment]
Awesome, thank you very much! I did not know I needed to connect a headset.

**Comment by danwillm** [comment]
Great, no problem. Going to close this now but feel free to reach out if you have any other problems.
