### ISSUE TITLE
[Idea] Linear potentiometers

### ISSUE THREAD

**Issue by Hexality** [LucidVR/lucidgloves#43]
My idea was to make this work using linear potentiometers
![image](https://user-images.githubusercontent.com/17398632/145050423-b2d906a6-a271-492d-aeea-39df97b86fa2.png)
(example)
instead of regular ones with a push-back motor attached to make it less bulky.

do you think that would work?

**Comment by LittleNyanCat** [comment]
Yes, it's been discussed quite extensively in our discord server, they work without any software changes needed

**Comment by Hexality** [comment]
nice, thank you.
