### ISSUE TITLE
potentionometer wont work?

### ISSUE THREAD

**Issue by Philliboyxd** [LucidVR/lucidgloves#46]
hi guys i finished my left glove by using all the thinks lucas has. i wired everything to the esp32 wroom-32 v1 mpdul and when i go to the serial port und move my thumb and pint finger the numbers change but when i move my pinky or middle finger the numbers are all the same :( Pls help me and i wired everthing to the pins and change it in the ide to the pins that i use

**Comment by LittleNyanCat** [comment]
What pins did you use? Some pins don't have ADCs and thus can't be used for the pots

**Comment by Philliboyxd** [comment]
i used g34,g35,g32,g25,g26

**Comment by LittleNyanCat** [comment]
Alright, all of those have ADCs. Double check your wiring then, that's always the problem everyone tends to have. Just because it looks good doesn't mean it is good

**Comment by Philliboyxd** [comment]
ok i checkt all of it and all are conecctect perfect to the potetinomiter as well to the dev board
can there be any other problem?

**Comment by LittleNyanCat** [comment]
How did you "checkt" it?

**Comment by Philliboyxd** [comment]
i pull the wire and look at this if its connected to the board and potentionometer. is it wrong?

**Comment by LittleNyanCat** [comment]
Check if there is an actual proper connection with a multimeter

**Comment by Philliboyxd** [comment]
multimeter?

**Comment by LittleNyanCat** [comment]
Yes. Multimeters are an essential tool when doing anything electronics related

**Comment by Philliboyxd** [comment]
ah that the wires are not broken ?

**Comment by Philliboyxd** [comment]
what problem culd be there anyways `?
