### ISSUE TITLE
Suggestions for the 3D models.

### ISSUE THREAD

**Issue by Nitwel** [LucidVR/lucidgloves#5]
I'm currently printing the parts for the glove and noticed some minor problems with the 3d models that could be improved upon.

1. The tensioner has this small corner arround it which my prusa mini couldn't handle even on 0.10mm layer height so the casing wouldn't hold. I added a bigger corner to hold on to which was much easier to print even on 0.25mm layer height. So if you'd like you could add this to the tensioner.
![grafik](https://user-images.githubusercontent.com/22577866/121206679-f65f3f00-c878-11eb-986e-f9f458502ee2.png)

2. The overhang on the spool hoder could cause trouble when printing so adding a soother edge here could improve the prints:
![grafik](https://user-images.githubusercontent.com/22577866/121207095-4ccc7d80-c879-11eb-8c2a-07fd4d3ae0a5.png)

Other than that the 3D Models are really well designed and I'm really excited to test the glove out!
Thank you so much for comming up with this idea and making it a reality. ❤️

**Comment by lucas-vrtech** [comment]
Yeah, I have some printability improvements coming up in prototype 4 soon. I'll make some changes to the snap ridge you mentioned, but unfortunately adding a chamfer to the spool like in your second image may be problematic as in my testing it sometimes guides the string off of the spool requiring you to take it apart and fix
