### ISSUE TITLE
OpenVR Init Error! Err: 110, Please kill SteamVR processes (VR Server) in Task Manager and try again.

### ISSUE THREAD

**Issue by Benjamin5678** [LucidVR/lucidgloves#50]
When I launch the OpenGloves app in steam I get this error. I checked task manager and had no "VR Server" or SteamVr proccess and I even killed all my background oculus tasks to be sure. I'm not sure what other information I should provide.

**Comment by Benjamin5678** [comment]
Error was due to SteamVR not being installed. Pretty bad error message if you ask me.

**Comment by lucas-vrtech** [comment]
Glad you were able to figure it out. Indeed, SteamVR is one of the requirements for OpenGloves. I'll talk to Dan and see if there's any way we can better document that in the UI.

For future reference, this issue would be more appropriately placed in https://github.com/LucidVR/opengloves-ui/issues.
(Or also the OpenGloves repo would be fine too)
Thanks
