### ISSUE TITLE
Potentiometers are too high friction, don't retract quickly

### ISSUE THREAD

**Issue by The15thGamer** [LucidVR/lucidgloves#54]
Building the spools, the potentiometers used are the same WL Brass potentiometers as listed in the wiki, linked here: https://www.amazon.com/gp/product/B07VQTFFGC 
Also using the same badge reel springs as directed. But the spool retracts very slowly, and the potentiometers seem to be really high friction and are causing this lag.

**Comment by LittleNyanCat** [comment]
Common issue, check the FAQ in our discord server

**Comment by The15thGamer** [comment]
> Common issue, check the FAQ in our discord server

Than you! Will do.
