### ISSUE TITLE
Will the parts from V3 be compatible with V4? And some games use buttons for say dropping a mag or for slo-mo, how do you create button inputs without buttons?

### ISSUE THREAD

**Issue by PetraSpaceRock** [LucidVR/lucidgloves#6]
I would like to know this because I am planning on building these but I am not sure if I will be able to play my favorite games using it.

**Comment by danwillm** [comment]
The designs for v4 are still not finalised - once it's out we will be able to confirm.

The firmware allows you to use 3 gestures: grab, pinch and trigger which can be used in place of buttons. Aside from those, it's recommend to use joysticks/buttons - it's often a better experience than trying to use gestures.

SteamVR games should all work fine with the gloves, though let us know if you run into issues.

I'm going to close this issue but let us know if you run into any issues.

Thanks.
