### ISSUE TITLE
No download link for 4.0 RigidMount_rightHand.stl

### ISSUE THREAD

**Issue by aakoch** [LucidVR/lucidgloves#62]
Something's goofy about RigidMount_rightHand.stl. There's no download link like there is for the left hand. I can view the raw blob,  but not sure it would download correctly. I guess I can always try. Anyway, just a heads up.

**Comment by danwillm** [comment]
This is a problem with GitHub by the looks of it. It is recommened to download the entire repo (either with git or using the green download button to download as zip) to get the parts, instead of downloading them individually. Let us know if you need any help with anything, we'd by happy to help.
