### ISSUE TITLE
Can't upload to development board

### ISSUE THREAD

**Issue by GZXH123** [LucidVR/lucidgloves#65]
![javaw_beSmqd4QE2](https://user-images.githubusercontent.com/102854435/161380499-07db3a89-734c-49d3-9417-a50b839418d7.png)

**Comment by LittleNyanCat** [comment]
You must install the ESP32 as a devboard on your Arduino IDE. Follow the [firmware setup guide](https://github.com/LucidVR/lucidgloves/wiki/Firmware-Setup-and-Customization-Tutorial).
