### ISSUE TITLE
Right hand RigidMount of prototype 4 does not have a download button

### ISSUE THREAD

**Issue by TechnicallyOffbeat** [LucidVR/lucidgloves#66]
Prototype 4's [left hand](https://github.com/LucidVR/lucidgloves/blob/main/hardware/Prototype4/RigidMount_leftHand.STL) rigid mount has a download button and seems to be working as intended.  
The [right hand](https://github.com/LucidVR/lucidgloves/blob/main/hardware/Prototype4/RigidMount_rightHand.STL) rigid mount does not have a download button, and is significantly larger for a file that should be basically the same as the left (76KB vs 374KB).

**Comment by Burritoclock** [comment]
Same issue here

**Comment by danwillm** [comment]
it is recommended to download the entire repository, then use the files from the download. You can download the repo by pressing the green code button on the homepage, then pressing download zip.
