### ISSUE TITLE
Firmware cannot be compiled when using a different esp32 eg(heltec esp32 wifi)

### ISSUE THREAD

**Issue by AikoKiss** [LucidVR/lucidgloves#69]
Leaves error like Led not a type if not compiled with esp32dev

**Comment by JohnRThomas** [comment]
Please open this issue on my fork as the problem is there :)

https://github.com/JohnRThomas/FlexiaGloves/issues

@danwillm I think you can close this

**Comment by danwillm** [comment]
Cool, thanks, will do!
