### ISSUE TITLE
Logo Font

### ISSUE THREAD

**Issue by darthnithin** [LucidVR/lucidgloves#76]
I’m attempting to vectorize the logo, It would be helpful to know what Font the logo uses, and if the hand symbol is bespoke or from a icon pack.

**Comment by CaelanTheCoder** [comment]
I'm sure there's algorithms to convert bitmap to vector and it wouldn't be that hard since there's only black and white

**Comment by lucas-vrtech** [comment]
The font is Acumin Variable Concept, and the logo is custom.
